# Generated by Django 2.1.3 on 2020-08-22 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0002_auto_20200822_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_list', to='myform.Survey'),
        ),
    ]
