# Generated by Django 2.1.3 on 2020-08-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0005_auto_20200822_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
