# Generated by Django 2.1.3 on 2020-08-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0008_answer_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
